var translationsEN = {
  firstName: "First name",
  lastName: "Last name",
  email: "Email",
  companyName: "Company Name",
  position: "Position",
  phone: "Telephone",
  address1: "Address",
  address2: "Address additional",
  zipCode: "Post code",
  city: "City",
  listCountry: "Country",
  vatNumber: "VAT Number",
  website: "Website",
  fonction: "Job Title",
  category: "Category",
  category_presse: "Category",
  departement: "Store Type",
  interest: "Interest",
  productType: "Product Type",
  visitReason: "Main reasons for your visit",
  newsletter: "Newsletter Signup",
  publication: "Publication type",
  visitReasonPresse: "Main reasons for your visit",
  submit: "Register to the event",
  exhibitors: "Exhibitors",
  exhibitor_guest_category_id: "Exhibitor category ID",
  generating_badge: "Generating badge",
  download: 'Download',
  badge: "Badge",
  add: 'Add',
  country: "Country",
  badges_quota: "Generated badges",
  quota: "Quota",
  generated_badge: "Generated badges",
  badgesQuotaStatsPhrase1: "You have an overall badge requests capacity of",
  badgesQuotaStatsPhrase2: ". You can still ask for",
  // ----------------- Countries --------------------
  FRA: 'France',
  AFG: 'Afghanistan',
  ZAF: 'South Africa',
  ALB: 'Albania',
  DZA: 'Algeria',
  DEU: 'Germany',
  AND: 'Andorra',
  AGO: 'Angola',
  AIA: 'Anguilla',
  ATG: 'Antigua and Barbuda',
  SAU: 'Saudi Arabia',
  ARG: 'Argentina',
  ARM: 'Armenia',
  ABW: 'Aruba',
  AUS: 'Australia',
  AUT: 'Austria',
  AZE: 'Azerbaijan',
  BHS: 'Bahamas',
  BHR: 'Bahrain',
  BGD: 'Bangladesh',
  BRB: 'Barbados',
  BLR: 'Belarus',
  BEL: 'Belgium',
  BLZ: 'Belize',
  BEN: 'Benin',
  BMU: 'Bermuda',
  BTN: 'Bhutan',
  BOL: 'Bolivia (Plurinational State of)',
  BES: 'Bonaire, Sint Eustatius and Saba',
  BIH: 'Bosnia and Herzegovina',
  BWA: 'Botswana',
  BRA: 'Brazil',
  BRN: 'Brunei Darussalam',
  BGR: 'Bulgaria',
  BFA: 'Burkina Faso',
  BDI: 'Burundi',
  CPV: 'Cabo Verde',
  KHM: 'Cambodia',
  CMR: 'Cameroon',
  CAN: 'Canada',
  CHL: 'Chile',
  CHN: 'China',
  HKG: 'China, Hong Kong Special Administrative Region',
  MAC: 'China, Macao Special Administrative Region',
  CYP: 'Cyprus',
  COL: 'Colombia',
  COM: 'Comoros',
  COG: 'Congo',
  CRI: 'Costa Rica',
  CIV: 'Côte d\'Ivoire',
  HRV: 'Croatia',
  CUB: 'Cuba',
  CUW: 'Curaçao',
  DNK: 'Denmark',
  DJI: 'Djibouti',
  DMA: 'Dominica',
  EGY: 'Egypt',
  SLV: 'El Salvador',
  ARE: 'United Arab Emirates',
  ECU: 'Ecuador',
  ERI: 'Eritrea',
  ESP: 'Spain',
  EST: 'Estonia',
  PSE: 'State of Palestine',
  USA: 'USA',
  ETH: 'Ethiopia',
  MKD: 'The former Yugoslav Republic of Macedonia',
  RUS: 'Russian Federation',
  FJI: 'Fiji',
  FIN: 'Finland',
  GUF: 'French Guiana',
  GAB: 'Gabon',
  GMB: 'Gambia',
  GEO: 'Georgia',
  GHA: 'Ghana',
  GIB: 'Gibraltar',
  GRC: 'Greece',
  GRL: 'Greenland',
  GRD: 'Grenada',
  GLP: 'Guadeloupe',
  GUM: 'Guam',
  GTM: 'Guatemala',
  GGY: 'Guernsey',
  GIN: 'Guinea',
  GNB: 'Guinea-Bissau',
  GNQ: 'Equatorial Guinea',
  GUY: 'Guyana',
  HTI: 'Haiti',
  HND: 'Honduras',
  HUN: 'Hungary',
  IMN: 'Isle of Man',
  NFK: 'Norfolk Island',
  CYM: 'Cayman Islands',
  COK: 'Cook Islands',
  ALA: 'Åland Islands',
  FLK: 'Falkland Islands (Malvinas)',
  FRO: 'Faeroe Islands',
  MNP: 'Northern Mariana Islands',
  MHL: 'Marshall Islands',
  SLB: 'Solomon Islands',
  SJM: 'Svalbard and Jan Mayen Islands',
  TCA: 'Turks and Caicos Islands',
  VIR: 'United States Virgin Islands',
  VGB: 'British Virgin Islands',
  WLF: 'Wallis and Futuna Islands',
  IND: 'India',
  IDN: 'Indonesia',
  IRN: 'Iran (Islamic Republic of)',
  IRQ: 'Iraq',
  IRL: 'Ireland',
  ISL: 'Iceland',
  ISR: 'Israel',
  ITA: 'Italy',
  JAM: 'Jamaica',
  JPN: 'Japan',
  JEY: 'Jersey',
  JOR: 'Jordan',
  KAZ: 'Kazakhstan',
  KEN: 'Kenya',
  KGZ: 'Kyrgyzstan',
  KIR: 'Kiribati',
  KWT: 'Kuwait',
  LSO: 'Lesotho',
  LVA: 'Latvia',
  LBN: 'Lebanon',
  LBR: 'Liberia',
  LBY: 'Libya',
  LIE: 'Liechtenstein',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  MDG: 'Madagascar',
  MYS: 'Malaysia',
  MWI: 'Malawi',
  MDV: 'Maldives',
  MLI: 'Mali',
  MLT: 'Malta',
  MAR: 'Morocco',
  MTQ: 'Martinique',
  MUS: 'Mauritius',
  MRT: 'Mauritania',
  MYT: 'Mayotte',
  MEX: 'Mexico',
  FSM: 'Micronesia (Federated States of)',
  MCO: 'Monaco',
  MNG: 'Mongolia',
  MNE: 'Montenegro',
  MSR: 'Montserrat',
  MOZ: 'Mozambique',
  MMR: 'Myanmar',
  NAM: 'Namibia',
  NRU: 'Nauru',
  NPL: 'Nepal',
  NIC: 'Nicaragua',
  NER: 'Niger',
  NGA: 'Nigeria',
  NIU: 'Niue',
  NOR: 'Norway',
  NCL: 'New Caledonia',
  NZL: 'New Zealand',
  OMN: 'Oman',
  UGA: 'Uganda',
  UZB: 'Uzbekistan',
  PAK: 'Pakistan',
  PLW: 'Palau',
  PAN: 'Panama',
  PNG: 'Papua New Guinea',
  PRY: 'Paraguay',
  NLD: 'Netherlands',
  PER: 'Peru',
  PHL: 'Philippines',
  PCN: 'Pitcairn',
  POL: 'Poland',
  PYF: 'French Polynesia',
  PRI: 'Puerto Rico',
  PRT: 'Portugal',
  QAT: 'Qatar',
  SYR: 'Syrian Arab Republic',
  CAF: 'Central African Republic',
  KOR: 'Republic of Korea',
  COD: 'Democratic Republic of the Congo',
  LAO: 'Lao People\'s Democratic Republic',
  MDA: 'Republic of Moldova',
  DOM: 'Dominican Republic',
  PRK: 'Democratic People\'s Republic of Korea',
  CZE: 'Czech Republic',
  TZA: 'United Republic of Tanzania',
  REU: 'Réunion',
  ROU: 'Romania',
  GBR: 'United Kingdom of Great Britain and Northern Ireland',
  RWA: 'Rwanda',
  ESH: 'Western Sahara',
  BLM: 'Saint Barthélemy',
  SHN: 'Saint Helena',
  KNA: 'Saint Kitts and Nevis',
  LCA: 'Saint Lucia',
  MAF: 'Saint Martin (French part)',
  SXM: 'Sint Maarten (Dutch part)',
  SMR: 'San Marino',
  SPM: 'Saint Pierre and Miquelon',
  VAT: 'Holy See',
  VCT: 'Saint Vincent and the Grenadines',
  WSM: 'Samoa',
  ASM: 'American Samoa',
  STP: 'Sao Tome and Principe',
  SEN: 'Senegal',
  SRB: 'Serbia',
  SYC: 'Seychelles',
  SLE: 'Sierra Leone',
  SGP: 'Singapore',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
  SOM: 'Somalia',
  SDN: 'Sudan',
  SSD: 'South Sudan',
  LKA: 'Sri Lanka',
  SWE: 'Sweden',
  CHE: 'Switzerland',
  SUR: 'Suriname',
  SWZ: 'Swaziland',
  TJK: 'Tajikistan',
  TCD: 'Chad',
  THA: 'Thailand',
  TLS: 'Timor-Leste',
  TGO: 'Togo',
  TKL: 'Tokelau',
  TON: 'Tonga',
  TTO: 'Trinidad and Tobago',
  TUN: 'Tunisia',
  TKM: 'Turkmenistan',
  TUR: 'Turkey',
  TUV: 'Tuvalu',
  UKR: 'Ukraine',
  URY: 'Uruguay',
  VUT: 'Vanuatu',
  VEN: 'Venezuela (Bolivarian Republic of)',
  VNM: 'Viet Nam',
  YEM: 'Yemen',
  ZMB: 'Zambia',
  ZWE: 'Zimbabwe'
};
window.I18n.translations.en = translationsEN;
window.I18n.availableLocales.push("en");
