var translationsFR = {
  firstName: "Prénom",
  lastName: "Nom",
  email: "E-mail",
  companyName: "Nom de la société",
  position: "Poste",
  phone: "Téléphone",
  address1: "Adresse",
  address2: "Complément d'adresse",
  zipCode: "Code postal",
  city: "Ville",
  listCountry: "Pays",
  vatNumber: "Numéro de TVA",
  website: "Site web",
  fonction: "Titre du poste",
  category: "Catégorie",
  category_presse: "Catégorie",
  departement: "Département",
  interest: "Intérêt",
  productType: "Type de produit",
  visitReason: "Les raisons de votre visite",
  newsletter: "Inscription aux newsletters",
  publication: "Type de publication",
  visitReasonPresse: "Les raisons de votre visite",
  submit: "S'inscrire à l'évènement",
  exhibitors: "Exposants",
  exhibitor_guest_category_id: "ID de la catégorie des Badges Exposant",
  generating_badge: "En cours de génération",
  download: "Télécharger",
  badge: 'Badge',
  add: "Ajouter",
  country: "Pays",
  badges_quota: "Nombre de badges générés",
  quota: "Quota",
  generated_badge: "Badges générés",
  badgesQuotaStatsPhrase1: "Vous avez un quota de",
  badgesQuotaStatsPhrase2: "badges nominatifs. Vous pouvez encore en demander",

  // -------------------- Countries ---------------------
  FRA: 'France',
  AFG: 'Afghanistan',
  ZAF: 'Afrique du Sud',
  ALB: 'Albanie',
  DZA: 'Algérie',
  DEU: 'Allemagne',
  AND: 'Andorre',
  AGO: 'Angola',
  AIA: 'Anguilla',
  ATG: 'Antigua-et-Barbuda',
  SAU: 'Arabie saoudite',
  ARG: 'Argentine',
  ARM: 'Arménie',
  ABW: 'Aruba',
  AUS: 'Australie',
  AUT: 'Autriche',
  AZE: 'Azerbaïdjan',
  BHS: 'Bahamas',
  BHR: 'Bahreïn',
  BGD: 'Bangladesh',
  BRB: 'Barbade',
  BLR: 'Bélarus',
  BEL: 'Belgique',
  BLZ: 'Belize',
  BEN: 'Bénin',
  BMU: 'Bermudes',
  BTN: 'Bhoutan',
  BOL: 'Bolivie (État plurinational de)',
  BES: 'Bonaire, Saint-Eustache et Saba',
  BIH: 'Bosnie-Herzégovine',
  BWA: 'Botswana',
  BRA: 'Brésil',
  BRN: 'Brunéi Darussalam',
  BGR: 'Bulgarie',
  BFA: 'Burkina Faso',
  BDI: 'Burundi',
  CPV: 'Cabo Verde',
  KHM: 'Cambodge',
  CMR: 'Cameroun',
  CAN: 'Canada',
  CHL: 'Chili',
  CHN: 'Chine',
  HKG: 'Chine, région administrative spéciale de Hong Kong',
  MAC: 'Chine, région administrative spéciale de Macao',
  CYP: 'Chypre',
  COL: 'Colombie',
  COM: 'Comores',
  COG: 'Congo',
  CRI: 'Costa Rica',
  CIV: 'Côte d\'Ivoire',
  HRV: 'Croatie',
  CUB: 'Cuba',
  CUW: 'Curaçao',
  DNK: 'Danemark',
  DJI: 'Djibouti',
  DMA: 'Dominique',
  EGY: 'Égypte',
  SLV: 'El Salvador',
  ARE: 'Émirats arabes unis',
  ECU: 'Équateur',
  ERI: 'Érythrée',
  ESP: 'Espagne',
  EST: 'Estonie',
  PSE: 'État de Palestine',
  USA: 'États-Unis d\'Amérique',
  ETH: 'Éthiopie',
  MKD: 'Ex-République yougoslave de Macédoine',
  RUS: 'Fédération de Russie',
  FJI: 'Fidji',
  FIN: 'Finlande',
  GUF: 'Guyane française',
  GAB: 'Gabon',
  GMB: 'Gambie',
  GEO: 'Géorgie',
  GHA: 'Ghana',
  GIB: 'Gibraltar',
  GRC: 'Grèce',
  GRL: 'Groenland',
  GRD: 'Grenade',
  GLP: 'Guadeloupe',
  GUM: 'Guam',
  GTM: 'Guatemala',
  GGY: 'Guernesey',
  GIN: 'Guinée',
  GNB: 'Guinée-Bissau',
  GNQ: 'Guinée équatoriale',
  GUY: 'Guyana',
  HTI: 'Haïti',
  HND: 'Honduras',
  HUN: 'Hongrie',
  IMN: 'Île de Man',
  NFK: 'Île Norfolk',
  CYM: 'Îles Caïmanes',
  COK: 'Îles Cook',
  ALA: 'Îles d\'Åland',
  FLK: 'Îles Falkland (Malvinas)',
  FRO: 'Îles Féroé',
  MNP: 'Îles Mariannes septentrionales',
  MHL: 'Îles Marshall',
  SLB: 'Îles Salomon',
  SJM: 'Îles Svalbard-et-Jan Mayen',
  TCA: 'Îles Turques-et-Caïques',
  VIR: 'Îles Vierges américaines',
  VGB: 'Îles Vierges britanniques',
  WLF: 'Îles Wallis-et-Futuna',
  IND: 'Inde',
  IDN: 'Indonésie',
  IRN: 'Iran (République islamique d\')',
  IRQ: 'Iraq',
  IRL: 'Irlande',
  ISL: 'Islande',
  ISR: 'Israël',
  ITA: 'Italie',
  JAM: 'Jamaïque',
  JPN: 'Japon',
  JEY: 'Jersey',
  JOR: 'Jordanie',
  KAZ: 'Kazakhstan',
  KEN: 'Kenya',
  KGZ: 'Kirghizistan',
  KIR: 'Kiribati',
  KWT: 'Koweït',
  LSO: 'Lesotho',
  LVA: 'Lettonie',
  LBN: 'Liban',
  LBR: 'Libéria',
  LBY: 'Libye',
  LIE: 'Liechtenstein',
  LTU: 'Lituanie',
  LUX: 'Luxembourg',
  MDG: 'Madagascar',
  MYS: 'Malaisie',
  MWI: 'Malawi',
  MDV: 'Maldives',
  MLI: 'Mali',
  MLT: 'Malte',
  MAR: 'Maroc',
  MTQ: 'Martinique',
  MUS: 'Maurice',
  MRT: 'Mauritanie',
  MYT: 'Mayotte',
  MEX: 'Mexique',
  FSM: 'Micronésie (États fédérés de)',
  MCO: 'Monaco',
  MNG: 'Mongolie',
  MNE: 'Monténégro',
  MSR: 'Montserrat',
  MOZ: 'Mozambique',
  MMR: 'Myanmar',
  NAM: 'Namibie',
  NRU: 'Nauru',
  NPL: 'Népal',
  NIC: 'Nicaragua',
  NER: 'Niger',
  NGA: 'Nigéria',
  NIU: 'Nioué',
  NOR: 'Norvège',
  NCL: 'Nouvelle-Calédonie',
  NZL: 'Nouvelle-Zélande',
  OMN: 'Oman',
  UGA: 'Ouganda',
  UZB: 'Ouzbékistan',
  PAK: 'Pakistan',
  PLW: 'Palaos',
  PAN: 'Panama',
  PNG: 'Papouasie-Nouvelle-Guinée',
  PRY: 'Paraguay',
  NLD: 'Pays-Bas',
  PER: 'Pérou',
  PHL: 'Philippines',
  PCN: 'Pitcairn',
  POL: 'Pologne',
  PYF: 'Polynésie française',
  PRI: 'Porto Rico',
  PRT: 'Portugal',
  QAT: 'Qatar',
  SYR: 'République arabe syrienne',
  CAF: 'République centrafricaine',
  KOR: 'République de Corée',
  COD: 'République démocratique du Congo',
  LAO: 'République démocratique populaire lao',
  MDA: 'République de Moldova',
  DOM: 'République dominicaine',
  PRK: 'République populaire démocratique de Corée',
  CZE: 'République tchèque',
  TZA: 'République-Unie de Tanzanie',
  REU: 'Réunion',
  ROU: 'Roumanie',
  GBR: 'Royaume-Uni de Grande-Bretagne et d\'Irlande du Nord',
  RWA: 'Rwanda',
  ESH: 'Sahara occidental',
  BLM: 'Saint-Barthélemy',
  SHN: 'Sainte-Hélène',
  KNA: 'Saint-Kitts-et-Nevis',
  LCA: 'Sainte-Lucie',
  MAF: 'Saint-Martin (partie française)',
  SXM: 'Saint-Martin (partie néerlandaise)',
  SMR: 'Saint-Marin',
  SPM: 'Saint-Pierre-et-Miquelon',
  VAT: 'Saint-Siège',
  VCT: 'Saint-Vincent-et-les Grenadines',
  WSM: 'Samoa',
  ASM: 'Samoa américaines',
  STP: 'Sao Tomé-et-Principe',
  SEN: 'Sénégal',
  SRB: 'Serbie',
  SYC: 'Seychelles',
  SLE: 'Sierra Leone',
  SGP: 'Singapour',
  SVK: 'Slovaquie',
  SVN: 'Slovénie',
  SOM: 'Somalie',
  SDN: 'Soudan',
  SSD: 'Soudan du Sud',
  LKA: 'Sri Lanka',
  SWE: 'Suède',
  CHE: 'Suisse',
  SUR: 'Suriname',
  SWZ: 'Swaziland',
  TJK: 'Tadjikistan',
  TCD: 'Tchad',
  THA: 'Thaïlande',
  TLS: 'Timor-Leste',
  TGO: 'Togo',
  TKL: 'Tokelau',
  TON: 'Tonga',
  TTO: 'Trinité-et-Tobago',
  TUN: 'Tunisie',
  TKM: 'Turkménistan',
  TUR: 'Turquie',
  TUV: 'Tuvalu',
  UKR: 'Ukraine',
  URY: 'Uruguay',
  VUT: 'Vanuatu',
  VEN: 'Venezuela (République bolivarienne du)',
  VNM: 'Viet Nam',
  YEM: 'Yémen',
  ZMB: 'Zambie',
  ZWE: 'Zimbabwe'
}
window.I18n.translations.fr = translationsFR;
window.I18n.availableLocales.push("fr");
