var translationsEN = {
  "firstName": {title:"First Name"},
  "lastName": {title:"Last Name"},
  "email": {title:"Billing email"},
  "emailBdd": {title:"Email for contacts export"},
  "companyName": {title:"Company Name"},
  "position": {title:"Position"},
  "madame": {title:"Mrs"},
  "monsieur": {title:"Mr"},
  "civilite": {title:"Title"},
  "mobilePhone": {title:"Mobile Phone"},
  "adresse1": {title:"Address (first line)"},
  "adresse2": {title:"Address (second line)"},
  "adresse3": {title:"Address (third line)"},
  "city": {title:"City"},
  "zipCode": {title:"Zip Code"},
  "country": {title:"Country"},
  "paymentMerchantType": {title:"Payment Type"},
  "creditCard": {title:"Credit card"},
  "check": {title:"Check"},
  "bankTransfer": {title:"Bank transfer"},
}
