var translationsFR = {
  "firstName": {title:"Prénom"},
  "lastName": {title:"Nom"},
  "email": {title:"Email de facturation"},
  "emailBdd": {title:"Email réception base de données"},
  "companyName": {title:"Société"},
  "position": {title:"Fonction"},
  "madame": {title:"Mme"},
  "monsieur": {title:"M."},
  "civilite": {title:"Civilité"},
  "mobilePhone": {title:"Téléphone mobile"},
  "adresse1": {title:"Adresse (Ligne 1)"},
  "adresse2": {title:"Adresse (Ligne 2)"},
  "adresse3": {title:"Adresse (Ligne 3)"},
  "city": {title:"Ville"},
  "zipCode": {title:"Code postal"},
  "country": {title:"Pays"},
  "paymentMerchantType": {title:"Moyen de paiement"},
  "creditCard": {title:"Carte bancaire"},
  "check": {title:"Chèque"},
  "bankTransfer": {title:"Virement bancaire"},
}
